#!/usr/bin/env casa
#
# This script was auto-generated by ADMIT version 1.0.8 and may be overwritten;
# copy before editing. It expects to run from /mnt/documents-local/ASTR4998/astr-senior-thesis/workspace/statcont_admit_pipeline/products/.
# If you need to start from scratch:   rm -rf SerpS_TC_spw1.pbcor_cutout_180_180_100_line.fits.admit
#
# This flow processes a single data cube. To process other cubes in the same
# way, call this script with another cube file as the command line argument:
# % admit0.py CUBEFILE
#
import os, sys
import admit

# Command line processing.
  cubefile = '/mnt/documents-local/ASTR4998/astr-senior-thesis/workspace/statcont_admit_pipeline/products/SerpS_TC_spw1.pbcor_cutout_180_180_100_line.fits'
  projdir = 'SerpS_TC_spw1.pbcor_cutout_180_180_100_line.fits.admit'

# Master project.
p = admit.Project(projdir, commit=False)

# Flow tasks.
t0  = p.addtask(admit.Ingest_AT(file=cubefile))
t1  = p.addtask(admit.CubeStats_AT(ppp=True), [t0])
t2  = p.addtask(admit.Moment_AT(mom0clip=2.0, numsigma=[1]), [t0, t1])
t3  = p.addtask(admit.CubeSpectrum_AT(), [t0, t2])
t5  = p.addtask(admit.LineSegment_AT(maxgap=10, minchan=2, numsigma=10.0, csub=[0,0]), [t1, t3])
t6  = p.addtask(admit.ContinuumSub_AT(), [t0, t5])

# now on new cube  (t6,0) or t6 is the line cube     (t6,1) is the cont map
t7  = p.addtask(admit.CubeStats_AT(ppp=True), [t6])
t8  = p.addtask(admit.Moment_AT(mom0clip=2.0, numsigma=[1]), [t6, t7])
t9  = p.addtask(admit.CubeSpectrum_AT(), [t6, t8])

t10  = p.addtask(admit.LineID_AT(allowexotics=True, maxgap=10, minchan=2, numsigma=8.0, recomblevel='deep', tier1width=10.0, vlsr=8.0), [t7, t9])


# Update project.
p.run()