max_y: 50
promising_lines:
  2,4-Pentadiynylidyne:
  - 758
  - 761
  - 0
  - 0.6
  - l-C5H
  - 336.48597
  Acetone:
  - 327
  - 333
  - 0
  - 0.6
  - (CH3)2CO
  - 336.59088
  Aminoacetonitrile:
  - 237
  - 252
  - 0
  - 0.6
  - H2NCH2CN
  - 336.61244
  Cyanoacetylene:
  - 508
  - 709
  - 0
  - 0.6
  - HC3N
  - 336.52008
  Cyanoallene:
  - 802
  - 809
  - 0
  - 0.6
  - H2CCCHCN
  - 336.475
  Cyanoformaldehyde:
  - 835
  - 869
  - 0
  - 0.6
  - CNCHO
  - 336.46699
  Ethyl Cyanide:
  - 0
  - 31
  - 0
  - 0.6
  - CH313CH2CN
  - 336.66812
  Ethylene Glycol:
  - 76
  - 100
  - 0
  - 0.6
  - g'Ga-(CH2OH)2
  - 336.65001
  Ethynyl:
  - 97
  - 203
  - 0
  - 0.6
  - 13CCH
  - 336.63657
  Formyl Radical:
  - 386
  - 413
  - 0
  - 0.6
  - HCO
  - 336.57107
  Glycolaldehyde:
  - 222
  - 229
  - 0
  - 0.6
  - cis-CH2OHCHO
  - 336.61618
  Methyl Formate:
  - 799
  - 805
  - 0
  - 0.6
  - CH3OCHO
  - 336.47563
  Vinyl Cyanide:
  - 70
  - 73
  - 0
  - 0.6
  - CH213CHCN
  - 336.65305
  gauche-Ethanol:
  - 815
  - 835
  - 0
  - 0.6
  - g-CH3CH2OH
  - 336.4694
vlsr: 8.0
