max_y: 120
promising_lines:
  Acetaldehyde:
  - 502
  - 515
  - 0
  - 0.6
  - CH3CHO
  - 334.93139
  Acetic Acid:
  - 70
  - 80
  - 0
  - 0.6
  - CH3COOH
  - 335.77985
  Acetone:
  - 59
  - 70
  - 0
  - 0.6
  - (CH3)2CO
  - 335.80291
  Aminoacetonitrile:
  - 115
  - 118
  - 0
  - 0.6
  - H2NCH2CN
  - 335.69558
  Ammonia:
  - 186
  - 210
  - 0
  - 0.6
  - NHD2
  - 335.51385
  Carbon Monophosphide:
  - 842
  - 851
  - 0
  - 0.6
  - CP
  - 334.26182
  Cyanic acid:
  - 229
  - 233
  - 0
  - 0.6
  - HOCN
  - 335.47103
  Cyclopropenylidene:
  - 414
  - 428
  - 0
  - 0.6
  - c-H13CCCH
  - 335.08781
  Ethyl Cyanide:
  - 35
  - 49
  - 0
  - 0.6
  - CH3CH2CN
  - 335.84026
  Ethylene Glycol:
  - 424
  - 433
  - 0
  - 0.6
  - g'Ga-(CH2OH)2
  - 335.07602
  Formaldehyde:
  - 49
  - 59
  - 0
  - 0.6
  - H2C18O
  - 335.81594
  Formic Acid:
  - 101
  - 118
  - 0
  - 0.6
  - t-H13COOH
  - 335.71489
  Glycolaldehyde:
  - 115
  - 118
  - 0
  - 0.6
  - cis-CH2OHCHO
  - 335.69367
  Methanol:
  - 108
  - 117
  - 0
  - 0.6
  - CH3OHvt=0
  - 335.7015
  Methyl Formate:
  - 7
  - 18
  - 0
  - 0.6
  - CH3OCHO
  - 335.89969
  Methylamine:
  - 75
  - 101
  - 0
  - 0.6
  - CH3NH2
  - 335.74509
  Oxoethenylidene:
  - 596
  - 612
  - 0
  - 0.6
  - CCO
  - 334.75876
  Propenal:
  - 10
  - 35
  - 0
  - 0.6
  - t-CH2CHCHO
  - 335.86616
  Protonated Carbon Dioxide:
  - 579
  - 585
  - 0
  - 0.6
  - HOCO+
  - 334.78159
  Sulfur Dioxide:
  - 908
  - 909
  - 0
  - 0.6
  - 33SO2
  - 334.14626
  Thioformaldehyde:
  - 483
  - 502
  - 0
  - 0.6
  - H213CS
  - 334.94932
  Vinyl Alcohol:
  - 808
  - 811
  - 0
  - 0.6
  - s-H2CCHOH
  - 334.34291
  Water:
  - 238
  - 311
  - 0
  - 0.6
  - HDO
  - 335.3955
  gauche-Ethanol:
  - 213
  - 229
  - 0
  - 0.6
  - g-CH3CH2OH
  - 335.48609
  trans-Ethanol:
  - 145
  - 156
  - 0
  - 0.6
  - t-CH3CH2OH
  - 335.63059
vlsr: 8.0
